# Generated by Django 4.1.13 on 2024-04-19 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gstdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbuisness_register_gst', models.BooleanField(default=False)),
                ('gstin', models.IntegerField(null=True)),
                ('gstdate', models.TextField(null=True)),
                ('compostion_scheme', models.BooleanField(default=False)),
                ('compostion_scheme_percent', models.TextField(null=True)),
                ('import_export', models.BooleanField(default=False)),
                ('customduty_tracking', models.TextField(null=True)),
                ('digital_service', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.warehouseuser')),
            ],
        ),
    ]
