# Generated by Django 4.1.13 on 2024-04-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_gstdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstdetails',
            name='gstin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
