# Generated by Django 4.1.13 on 2024-04-19 09:07

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_gstdetails_gstin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstdetails',
            name='compostion_scheme_percent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gstdetails',
            name='customduty_tracking',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gstdetails',
            name='gstdate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Additem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.TextField()),
                ('item_image', models.ImageField(upload_to=app.models.upload_path)),
                ('item_name', models.TextField()),
                ('item_sku', models.TextField()),
                ('item_unit', models.TextField()),
                ('item_sac', models.TextField(blank=True)),
                ('returnable_item', models.BooleanField(default=False)),
                ('HSN_code', models.TextField(blank=True)),
                ('taxable', models.BooleanField(default=False)),
                ('exemptional_reson', models.TextField(blank=True)),
                ('sales_info', models.BooleanField(default=False)),
                ('selling_price', models.IntegerField(blank=True)),
                ('sales_account', models.TextField(blank=True)),
                ('sales_description', models.TextField(blank=True)),
                ('purchase_info', models.BooleanField(default=False)),
                ('cost_price', models.IntegerField(blank=True)),
                ('purchase_account', models.TextField(blank=True)),
                ('purchase_description', models.TextField(blank=True)),
                ('intrastate_tax', models.TextField()),
                ('interstate_tax', models.TextField()),
                ('track_inventory', models.BooleanField(default=False)),
                ('inventory_account', models.TextField(blank=True)),
                ('opening_stock', models.TextField(blank=True)),
                ('opening_stock_rate_per_unit', models.TextField(blank=True)),
                ('recorder_level', models.TextField(blank=True)),
                ('preffered_vendor', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.warehouseuser')),
            ],
        ),
    ]
