# Generated by Django 4.1.13 on 2024-04-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_gstdetails_compostion_scheme_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='HSN_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additem',
            name='cost_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additem',
            name='exemptional_reson',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additem',
            name='inventory_account',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additem',
            name='item_sac',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additem',
            name='opening_stock',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additem',
            name='opening_stock_rate_per_unit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additem',
            name='preffered_vendor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additem',
            name='purchase_account',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additem',
            name='purchase_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additem',
            name='recorder_level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additem',
            name='sales_account',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additem',
            name='sales_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additem',
            name='selling_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
