# Generated by Django 4.1.13 on 2024-04-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_preffered_vendor_additem_prefered_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additem',
            old_name='prefered_vendor',
            new_name='preferred_vendor',
        ),
    ]
