# Generated by Django 4.1.13 on 2024-04-19 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_prefered_vendor_additem_preferred_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_location', models.TextField()),
                ('fiscal_year', models.TextField()),
                ('currency', models.TextField()),
                ('language', models.TextField()),
                ('inventory_startdate', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.warehouseuser')),
            ],
        ),
    ]
