# Generated by Django 4.1.13 on 2024-04-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='additem',
            name='dimension',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='additem',
            name='ean',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='additem',
            name='isbn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='additem',
            name='manifacturer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='additem',
            name='mnp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='additem',
            name='upc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='additem',
            name='weight',
            field=models.TextField(blank=True, null=True),
        ),
    ]
