# Generated by Django 4.1.13 on 2024-04-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_additem_brand_additem_dimension_additem_ean_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additem',
            old_name='exemptional_reson',
            new_name='exemptional_reason',
        ),
    ]
